apiVersion: v1
kind: Service

metadata:
  name: express-service

spec:
  type: NodePort #exposes application outside the cluster

  selector:
    app: express-backend #Send traffic to Pods that have the label app=express-backend.

  ports:
    - port: 4000
      targetPort: 4000 #listening inside the container.
      nodePort: 30080 #port exposed by minikube